baseURL = "https://1nten.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "PaperMod"
[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]
